config/routes.rb
GEnterprise::Application.routes.draw do
  devise_for :admins

  authenticated :admin do
    root 'dashboard#index'
  end

  unauthenticated :admin do
    devise_scope :admin do
      get "/" => "devise/sessions#new"
    end
  end

  resources :stocks

  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/denomination.rb
class Denomination < ActiveRecord::Base
  belongs_to :provider
end

app/models/provider.rb
class Provider < ActiveRecord::Base
  belongs_to :stock
  has_many :denominations
  accepts_nested_attributes_for :denominations, allow_destroy: true,
									reject_if: proc { |a| a[:name].blank? }
end

app/models/stock.rb
class Stock < ActiveRecord::Base
	has_many :providers
	accepts_nested_attributes_for :providers, allow_destroy: true,
									reject_if: proc { |provider| provider[:name].blank? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_filter :authenticate_admin!
	def index
	end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
	before_filter :authenticate_admin!

	def index	
	end

	def new
		@stock = Stock.new
		2.times do
			provider = @stock.providers.build
			4.times { provider.denominations.build }
		end
	end

	def create
		@stock = Stock.create(stock_params)
		if @stock.save
			flash[:notice] = "Order was successfully recorded"
			redirect_to stocks_path
		else
			render 'new'
		end
	end

	private

		def stock_params
			params.require(:stock).permit(:name, providers_attributes: [:name, denominations_attributes: [:name, :quantity, :buying_price, :_destroy]])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def link_to_add_fields(name, f, association)
	    new_object = f.object.class.reflect_on_association(association).klass.new
	    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
	      render(association.to_s.singularize + "_fields", :f => builder)
	    end
	    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  	end

  	def active_class(controller)
  		'active' if controller_name == controller
  	end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/layouts/_navbar_side.html.erb
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">
            <li class="side-user hidden-xs">
                <img class="img-circle" src="https://lh5.googleusercontent.com/-b0-k99FZlyE/AAAAAAAAAAI/AAAAAAAAAAA/eu7opA4byxI/photo.jpg?sz=150" alt="">
                <p class="welcome">
                    <i class="fa fa-key"></i> Logged in as
                </p>
                <p class="name tooltip-sidebar-logout">
                    Grace
                    <span class="last-name">Wanjiku</span>
                </p>
                <div class="clearfix"></div>
            </li>
            <li class="sidebar-search">
                <div class="input-group custom-search-form">
                    <input type="text" class="form-control" placeholder="Search...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
                <!-- /input-group -->
            </li>
            <li>
                <%= link_to raw('<i class="fa fa-dashboard fa-fw"></i> Dashboard'), root_path %>
            </li>
            <li class="<%= active_class('stocks') %>">
                <%= link_to raw('<i class="fa fa-bar-chart-o fa-fw"></i> Stock <span class="fa arrow"></span>'), '#' %>
                <ul class="nav nav-second-level">
                    <li>
                        <%= link_to "All Stock", stocks_path %>
                    </li>
                    <li>
                        <%= link_to "New Stock", new_stock_path %>
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>
            <li>
                <a href="tables.html"><i class="fa fa-table fa-fw"></i> Tables</a>
            </li>
            <li>
                <a href="forms.html"><i class="fa fa-edit fa-fw"></i> Forms</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-wrench fa-fw"></i> UI Elements<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="panels-wells.html">Panels and Wells</a>
                    </li>
                    <li>
                        <a href="buttons.html">Buttons</a>
                    </li>
                    <li>
                        <a href="notifications.html">Notifications</a>
                    </li>
                    <li>
                        <a href="typography.html">Typography</a>
                    </li>
                    <li>
                        <a href="grid.html">Grid</a>
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>
            <li>
                <a href="#"><i class="fa fa-sitemap fa-fw"></i> Multi-Level Dropdown<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="#">Second Level Item</a>
                    </li>
                    <li>
                        <a href="#">Second Level Item</a>
                    </li>
                    <li>
                        <a href="#">Third Level <span class="fa arrow"></span></a>
                        <ul class="nav nav-third-level">
                            <li>
                                <a href="#">Third Level Item</a>
                            </li>
                            <li>
                                <a href="#">Third Level Item</a>
                            </li>
                            <li>
                                <a href="#">Third Level Item</a>
                            </li>
                            <li>
                                <a href="#">Third Level Item</a>
                            </li>
                        </ul>
                        <!-- /.nav-third-level -->
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>
            <li class="active">
                <a href="#"><i class="fa fa-files-o fa-fw"></i> Sample Pages<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="blank.html">Blank Page</a>
                    </li>
                    <li>
                        <a href="login.html">Login Page</a>
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>
        </ul>
        <!-- /#side-menu -->
    </div>
    <!-- /.sidebar-collapse -->
</nav>
<!-- /.navbar-static-side -->

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <%= link_to "Grace Enterprise", root_path, class: "navbar-brand" %>
    </div>
    <!-- /.navbar-header -->

    <ul class="nav navbar-top-links navbar-right">
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-envelope fa-fw"></i>  <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-messages">
                <li>
                    <a href="#">
                        <div>
                            <strong>John Smith</strong>
                            <span class="pull-right text-muted">
                                <em>Yesterday</em>
                            </span>
                        </div>
                        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <strong>John Smith</strong>
                            <span class="pull-right text-muted">
                                <em>Yesterday</em>
                            </span>
                        </div>
                        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <strong>John Smith</strong>
                            <span class="pull-right text-muted">
                                <em>Yesterday</em>
                            </span>
                        </div>
                        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a class="text-center" href="#">
                        <strong>Read All Messages</strong>
                        <i class="fa fa-angle-right"></i>
                    </a>
                </li>
            </ul>
            <!-- /.dropdown-messages -->
        </li>
        <!-- /.dropdown -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-tasks fa-fw"></i>  <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-tasks">
                <li>
                    <a href="#">
                        <div>
                            <p>
                                <strong>Task 1</strong>
                                <span class="pull-right text-muted">40% Complete</span>
                            </p>
                            <div class="progress progress-striped active">
                                <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                                    <span class="sr-only">40% Complete (success)</span>
                                </div>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <p>
                                <strong>Task 2</strong>
                                <span class="pull-right text-muted">20% Complete</span>
                            </p>
                            <div class="progress progress-striped active">
                                <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                                    <span class="sr-only">20% Complete</span>
                                </div>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <p>
                                <strong>Task 3</strong>
                                <span class="pull-right text-muted">60% Complete</span>
                            </p>
                            <div class="progress progress-striped active">
                                <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                                    <span class="sr-only">60% Complete (warning)</span>
                                </div>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <p>
                                <strong>Task 4</strong>
                                <span class="pull-right text-muted">80% Complete</span>
                            </p>
                            <div class="progress progress-striped active">
                                <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                                    <span class="sr-only">80% Complete (danger)</span>
                                </div>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a class="text-center" href="#">
                        <strong>See All Tasks</strong>
                        <i class="fa fa-angle-right"></i>
                    </a>
                </li>
            </ul>
            <!-- /.dropdown-tasks -->
        </li>
        <!-- /.dropdown -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-bell fa-fw"></i>  <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-alerts">
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-comment fa-fw"></i> New Comment
                            <span class="pull-right text-muted small">4 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                            <span class="pull-right text-muted small">12 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-envelope fa-fw"></i> Message Sent
                            <span class="pull-right text-muted small">4 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-tasks fa-fw"></i> New Task
                            <span class="pull-right text-muted small">4 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-upload fa-fw"></i> Server Rebooted
                            <span class="pull-right text-muted small">4 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a class="text-center" href="#">
                        <strong>See All Alerts</strong>
                        <i class="fa fa-angle-right"></i>
                    </a>
                </li>
            </ul>
            <!-- /.dropdown-alerts -->
        </li>
        <!-- /.dropdown -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                </li>
                <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                </li>
                <li class="divider"></li>
                <li><%= link_to raw('<i class="fa fa-sign-out fa-fw"></i> Logout'),  destroy_admin_session_path, method: :delete %>
                </li>
            </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->

</nav>
<!-- /.navbar-static-top -->

<%= render 'layouts/navbar_side' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>

    <title><%= yield :title %></title>

    <!-- Core CSS - Include with every page -->
    <%= stylesheet_link_tag "application", media: "all" %>

</head>

<body>

    <div id="wrapper">

        <%= render 'layouts/navigation' %>


        <div id="page-wrapper">
            <div class="row">
                <div class="col-md-12">
                    <%= render 'shared/flash' %>
                </div>
                
            	<%= yield %>
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- Core Scripts - Include with every page -->
    <%= javascript_include_tag "application" %>

</body>

</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Login | Grace Enterprise</title>

    <!-- Core CSS - Include with every page -->
    <%= stylesheet_link_tag    "application", media: "all" %>

</head>

<body>

    <div class="container">
        <div class="row">
            <%= yield %>
        </div>
    </div>

    <!-- Core Scripts - Include with every page -->
    <%= javascript_include_tag "application" %>

</body>

</html>

app/views/shared/_flash.html.erb
<% if notice %>
  <div class="alert alert-dismissable alert-success">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <%= notice %>
  </div>
<% elsif alert %>
  <div class="alert alert-dismissable alert-danger">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <%= alert %>
  </div>
<% end %>

app/views/stocks/_denomination_fields.html.erb
<div class="row">
	<div class="col-md-4">
		<div class="form-group">
			<%= f.label :name %>
			<%= f.select :name, [ 'Bamba 10', 'Bamba 20', 'Bamba 50', 'Bamba 100', 'Bamba 250', 'Bamba 500', 'Bamba 1000'], { :prompt => 'Pick One' }, { class: "form-control" } %>
		</div>
	</div>
	<div class="col-md-3">
		<div class="form-group">
			<%= f.label :quantity %>
			<%= f.text_field :quantity, class: "form-control" %>
		</div>
	</div>
	<div class="col-md-3">
		<div class="form-group">
			<%= f.label :buying_price %>
			<%= f.text_field :buying_price, class: "form-control" %>
		</div>
	</div>
	<div class="col-md-2">
		<div class="form-group" style="margin-top: 30px;" >
			<%= f.hidden_field :_destroy %>
			<%= link_to_function raw("<i class='fa fa-times'></i> remove"), "remove_fields(this)" %>
		</div>
	</div>
</div>

app/views/stocks/_provider_fields.html.erb
<div class="col-md-6">
	<div class="panel panel-default">
	    <div class="panel-heading">
	        <i class="fa fa-sitemap"></i> Provider
	    </div>
	    <!-- /.panel-heading -->
	    <div class="panel-body">
		    <div class="form-group">
		    	<%= f.select :name, [ 'Safaricom', 'Airtel', 'Orange', 'Yu'], { :prompt => 'Select Provider' }, { class: "form-control" } %>
			</div>


			<legend><i class="fa fa-ticket"></i> Denominations</legend>
			<%= f.fields_for :denominations do |builder| %>
				<%= render 'denomination_fields', :f => builder %>
			<% end %>
			<div class="form-group">
				<%= link_to_add_fields raw("<i class='fa fa-plus-circle'></i> Add Denomination"), f, :denominations %>
			</div>
	        
	    </div>
	    <!-- /.panel-body -->
	</div>
</div>

app/views/stocks/new.html.erb
<div class="col-md-12">
	<h2><i class="fa fa-shopping-cart"></i> New Stock</h2>
	<hr>
	<%= form_for @stock, html: { role: "form" } do |f| %>
		<div class="form-group">
			<%= f.label :name %>
			<%= f.text_field :name, class: "form-control", value: "stock-#{Date.today}" %>
		</div>
		<div class="row">

			<%= f.fields_for :providers do |builder| %>

					<%= render 'provider_fields', :f => builder %>

			<% end %>
		</div>
		<div class="form-group">
			<%= link_to_add_fields raw("<i class='fa fa-plus-circle'></i> Add Providers"), f, :providers %>
		</div>

		<div class="form-group" style="clear: both;">
				<%= f.submit "Register Order", class: "btn btn-success btn-lg  up-40" %>
		</div>
	<% end %>
</div>